name: RandomTeleport
main: org.clapper.minecraft.randomteleport.RandomTeleportPlugin
author: "Brian M. Clapper"
version: 0.4
depend: [ScalaLibPlugin]
load: "POSTWORLD"
commands:
  rp:
    description: "Randomly teleport somewhere in the current world"
    usage: "Usage: /rp"
