# Generated $date
name: $name
main: org.clapper.bukkit.randomteleport.RandomTeleportPlugin
author: Brian M. Clapper
version: $version
depend: ["mc-scala-plugin"]
load: "POSTWORLD"
commands:
  rp:
    description: "Randomly teleport somewhere."
    usage: "/rp"
    permission: org.clapper.randomTeleport.enabled
permissions:
  org.clapper.randomTeleport.enabled:
    description: Whether or not you can use /rp
    default: false
  org.clapper.randomTeleport.immediate:
    description: "Whether or not you can teleport immediately, always."
    default: false
