# Generated @genTime@
name: @name@
main: @class@
author: "@author@"
version: @version@
depend: [ScalaLibPlugin]
load: "POSTWORLD"
commands:
  rp:
    description: "Randomly teleport somewhere."
    usage: "/rp"
